# Generated by Django 5.2 on 2025-04-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_pinlink_account_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinlink',
            name='status',
            field=models.CharField(default='Active'),
        ),
    ]
