# Generated by Django 5.2 on 2025-04-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0004_accountlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountlog',
            name='profile',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accountlog',
            name='email',
            field=models.CharField(),
        ),
    ]
