# Generated by Django 5.2 on 2025-04-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0005_accountlog_profile_alter_accountlog_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountlog',
            name='email',
            field=models.CharField(null=True),
        ),
    ]
