# Generated by Django 5.2 on 2025-04-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0006_alter_accountlog_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='ads_profile_id',
            field=models.CharField(blank=True, max_length=75),
        ),
    ]
