# Generated by Django 5.2 on 2025-04-17 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0007_account_ads_profile_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='ads_profile_id',
            new_name='profile_id',
        ),
    ]
